version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: GCloud Key
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run:
          name: Run Pytest
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            pytest -s -v
      - run:
          name: Run Pylint
          command: |
            pylint **/*.py
      - run:
          name: Run Black
          command: |
            black --check **/*.py

workflows:
  build_test:
    jobs:
      - run_tests
