version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout
      - run:
          name: GCloud Key
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run:
          name: Install python dependencies
          command: |
            virtualenv --python python3 .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            source .venv/bin/activate
            pytest -s -v

workflows:
  main:
    jobs:
      - test
